Revert "[ChromeDriver] Enable CQ tests on Mac/Windows"
This reverts commit 9de3051e3af2dec23fb303bd2784c8665a147f38.

Reason for revert: 
This causes Mac10.9 build bot failure. i.e.

chromedriver_py_tests chromedriver_py_tests
Run on OS: 'Mac-10.9'

Starting ChromeDriver 2.35.531399 (9de3051e3af2dec23fb303bd2784c8665a147f38) on port 9500
Only local connections are allowed.
testLoadUrl (__main__.ChromeDriverTest) ... ERROR

======================================================================
ERROR: testLoadUrl (__main__.ChromeDriverTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "../../chrome/test/chromedriver/test/run_py_tests.py", line 394, in setUp
    self._driver = self.CreateDriver()
  File "../../chrome/test/chromedriver/test/run_py_tests.py", line 316, in CreateDriver
    **kwargs)
  File "/b/swarm_slave/w/ir/chrome/test/chromedriver/test/../client/chromedriver.py", line 233, in __init__
    response = self._ExecuteCommand(Command.NEW_SESSION, params)
  File "/b/swarm_slave/w/ir/chrome/test/chromedriver/test/../client/chromedriver.py", line 284, in _ExecuteCommand
    response = self._executor.Execute(command, params)
  File "/b/swarm_slave/w/ir/chrome/test/chromedriver/test/../client/command_executor.py", line 193, in Execute
    response = self._http_client.getresponse()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1045, in getresponse
    response.begin()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 409, in begin
    version, status, reason = self._read_status()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 365, in _read_status
    line = self.fp.readline(_MAXLINE + 1)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 476, in readline
    data = self._sock.recv(self._rbufsize)
timeout: timed out

Original change's description:
> [ChromeDriver] Enable CQ tests on Mac/Windows
> 
> Previously, the commit queue only runs ChromeDriver tests on Linux.
> This CL expands the test to other desktop platforms, including Mac
> and Windows.
> 
> Bug: 793370
> Change-Id: I2a28d3a5c8371edc28566010739681acfac41c21
> Reviewed-on: https://chromium-review.googlesource.com/881641
> Reviewed-by: Caleb Rouleau <crouleau@chromium.org>
> Reviewed-by: John Budorick <jbudorick@chromium.org>
> Commit-Queue: John Chen <johnchen@chromium.org>
> Cr-Commit-Position: refs/heads/master@{#531399}

TBR=crouleau@chromium.org,johnchen@chromium.org,jbudorick@chromium.org

Change-Id: Ic872389bc30057948d59443ba1481b7344cfbab6
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Bug: 793370
Reviewed-on: https://chromium-review.googlesource.com/882702
Reviewed-by: Takashi Sakamoto <tasak@google.com>
Commit-Queue: Takashi Sakamoto <tasak@google.com>
Cr-Original-Commit-Position: refs/heads/master@{#531421}
Cr-Mirrored-From: https://chromium.googlesource.com/chromium/src
Cr-Mirrored-Commit: bd16c9a5dda0aedbd73dd8459bffe432d11e9941